Document: weeping-moon
Title: Debian weeping-moon Manual
Author: <insert document author here>
Abstract: This manual describes what weeping-moon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/weeping-moon/weeping-moon.sgml.gz

Format: postscript
Files: /usr/share/doc/weeping-moon/weeping-moon.ps.gz

Format: text
Files: /usr/share/doc/weeping-moon/weeping-moon.text.gz

Format: HTML
Index: /usr/share/doc/weeping-moon/html/index.html
Files: /usr/share/doc/weeping-moon/html/*.html
