#! /usr/bin/env bash

help() {
    cat <<__EOF__
    Module description:

    This just helps to install and configure automatic
    updates (SECURITY ONLY) for the server.
__EOF__
}

main() {
    echo -e "Please input your email."
    echo -e "Don't worry it will be written on the /etc/apt/apt.conf.d/50unattended-upgrades file"
    read -r email
    echo -e "[WARN] Configuring security updates"
    # Write to the apt.conf.d file
    echo ": Unattended-Upgrade::Allowed-Origins {
     \"\${distro_id}:\${distro_codename}-security\";
 //  \"\${distro_id}:\${distro_codename}-updates\";
 //  \"\${distro_id}:\${distro_codename}-proposed\";
 //  \"\${distro_id}:\${distro_codename}-backports\";
 };
 // Unattended-Upgrade::Mail \"$email\";" | sudo tee -a /etc/apt/apt.conf.d/50unattended-upgrades

    sudo apt-get install unattended-upgrades
    sudo dpkg-reconfigure -plow unattended-upgrades
    echo -e "[SUCCESS] Automatic security configured correctly"
    exit 0
}

case $1 in
    help) help;;
    *) main;;
esac

# 2020 - UpVent
