#! /usr/bin/env bash

help() {
    cat <<__EOF__
    Module description:

__EOF__
}

main() {
    echo "This module isn't ready yet!"
    exit 127;
}

case $1 in
    help) help;;
    *) main;;
esac

# 2020 - UpVent
