#! /usr/bin/env bash

help() {
    cat <<__EOF__
    Module description:

__EOF__
}

main() {
    echo -e "[WARN] Updating the system, please make sure an update is ABSOLUTELY neccesary"
    sudo apt update
    sudo apt upgrade
    sudo apt autoremove
    sudo apt autoclean
    echo -e "[SUCCESS] System updated successfully"
}

case $1 in
    help) help;;
    *) main;;
esac

# 2020 - UpVent
